"""ICS pipeline + HF upload orchestration for Qwen3.5-2B.

Sequence:
1. Auth HF (token injected from local env via bridge)
2. Download model (~4 GB) -> upload snapshot to HF dataset repo
3. Run a 1-layer GPTQ smoke test (sanity, fail-fast)
4. Run full ICS+GPTQ pipeline in background subprocess
5. After each stage, upload to HF (incremental, so partial work survives)
6. Run PPL benchmark (dequantized model vs BF16 baseline)
7. Final: upload full artifact + write README + commit summary

Designed to be uploaded to /content/run_pipeline.py on Colab, then
launched as `nohup python3 -u /content/run_pipeline.py > /content/pipeline.log 2>&1 &`.
Then Mavis polls /content/pipeline.log.
"""
from __future__ import annotations

import os
import sys
import time
import json
import math
import shutil
import traceback
from pathlib import Path

os.environ.setdefault("PYTHONUNBUFFERED", "1")

ICS_DIR = "/content/ICS"
sys.path.insert(0, ICS_DIR)

# Clear pycache so we get fresh imports
for root, dirs, files in os.walk(ICS_DIR):
    for d in dirs:
        if d == "__pycache__":
            shutil.rmtree(os.path.join(root, d), ignore_errors=True)
for mod in list(sys.modules):
    if mod.startswith("ics.") or mod.startswith("scripts."):
        del sys.modules[mod]
if "ics" in sys.modules:
    del sys.modules["ics"]


# ---------- logging ----------

LOG_PATH = Path("/content/pipeline.log")


def log(msg: str) -> None:
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line, flush=True)
    with LOG_PATH.open("a") as f:
        f.write(line + "\n")


# ---------- HF setup ----------

USER = None
MODEL_REPO = None
DATASET_REPO = None


def hf_setup() -> None:
    global USER, MODEL_REPO, DATASET_REPO
    from huggingface_hub import HfApi
    api = HfApi(token=os.environ["HF_TOKEN"])
    me = api.whoami()
    USER = me["name"]
    MODEL_REPO = f"{USER}/Qwen3.5-2B-ICS-INT4"
    DATASET_REPO = f"{USER}/ics-quantization-artifacts"
    log(f"hf_setup: USER={USER} MODEL_REPO={MODEL_REPO} DATASET_REPO={DATASET_REPO}")
    for repo_id, kind in [(MODEL_REPO, "model"), (DATASET_REPO, "dataset")]:
        try:
            api.create_repo(repo_id=repo_id, repo_type=kind, private=True, exist_ok=True, token=os.environ["HF_TOKEN"])
            log(f"  repo ready: https://huggingface.co/{repo_id} ({kind})")
        except Exception as e:
            log(f"  repo create error for {repo_id}: {e}")


def hf_upload(local_dir: str, repo_type: str, message: str, blocking: bool = False) -> dict:
    """Upload local_dir to HF as a background subprocess. Returns immediately
    unless blocking=True. The subprocess writes a .upload_marker.json on completion."""
    sys.path.insert(0, "/content")
    from upload_to_hf import upload_stage
    repo = MODEL_REPO if repo_type == "model" else DATASET_REPO
    log(f"hf_upload start: {local_dir} -> {repo} ({repo_type}) [{message}]")
    res = upload_stage(
        local_dir=local_dir,
        repo_id=repo,
        repo_type=repo_type,
        token=os.environ["HF_TOKEN"],
        message=message,
        wait=blocking,
        timeout_s=3600.0,
    )
    log(f"hf_upload submitted: pid={res.get('pid')} marker={res.get('marker_path')}")
    return res


def write_stage_readme(stage_dir: str, stage_name: str, extra_md: str = "") -> None:
    p = Path(stage_dir) / "README.md"
    base = f"""# {stage_name}

Generated by the ICS quantization pipeline (Qwen3.5-2B target, run at {time.strftime('%Y-%m-%d %H:%M:%S')}).

{extra_md}

## Contents

See `files.txt` for the full file listing at upload time.

## Provenance

- ICS pipeline: `/content/ICS` (git head at upload time)
- HF model repo: https://huggingface.co/{MODEL_REPO}
- HF dataset repo: https://huggingface.co/{DATASET_REPO}
"""
    p.write_text(base)
    files_txt = Path(stage_dir) / "files.txt"
    files_txt.write_text(
        "\n".join(
            sorted(
                f"{f.name}\t{f.stat().st_size}"
                for f in Path(stage_dir).rglob("*")
                if f.is_file() and not f.name.startswith(".")
            )
        )
    )


# ---------- perplexity (inline, self-contained) ----------

def compute_perplexity(model, tokenizer, texts: list[str], block_size: int = 512, device: str = "cuda") -> tuple[float, int]:
    """Compute total NLL-based perplexity over a list of texts."""
    import torch
    model.eval()
    total_nll = 0.0
    total_tokens = 0
    with torch.no_grad():
        for text in texts:
            enc = tokenizer(text, return_tensors="pt", truncation=False)
            input_ids = enc["input_ids"].to(device)
            if input_ids.numel() < 2:
                continue
            seq_len = input_ids.shape[1]
            for start in range(0, seq_len - 1, block_size):
                end = min(start + block_size, seq_len)
                if end - start < 2:
                    continue
                chunk = input_ids[:, start:end]
                out = model(input_ids=chunk, use_cache=False)
                logits = out.logits[:, :-1, :].float()
                labels = chunk[:, 1:]
                loss = torch.nn.functional.cross_entropy(
                    logits.reshape(-1, logits.shape[-1]),
                    labels.reshape(-1),
                    reduction="sum",
                )
                total_nll += float(loss.item())
                total_tokens += int(labels.numel())
    if total_tokens == 0:
        return float("nan"), 0
    return math.exp(total_nll / total_tokens), total_tokens


# ---------- main ----------

def main():
    LOG_PATH.write_text("")
    log("===== ICS Qwen3.5-2B pipeline START =====")

    import torch
    log(f"torch={torch.__version__} cuda={torch.cuda.is_available()} device={torch.cuda.get_device_name(0)}")
    log(f"VRAM free: {torch.cuda.mem_get_info()[0]/1e9:.1f} GB / {torch.cuda.mem_get_info()[1]/1e9:.1f} GB")

    # 0. Auth + repos
    hf_setup()

    # 1. Download model
    log("STEP 1: downloading Qwen3.5-2B")
    t0 = time.time()
    from huggingface_hub import snapshot_download
    qwen_path = snapshot_download(
        repo_id="Qwen/Qwen3.5-2B",
        local_dir="/content/Qwen3.5-2B",
        allow_patterns=["*.safetensors", "*.json", "*.txt", "*.jinja", "tokenizer*", "vocab*", "merges*", "generation_config*"],
    )
    log(f"  downloaded in {time.time()-t0:.1f}s to {qwen_path}")
    for f in sorted(Path(qwen_path).iterdir()):
        log(f"    {f.name}: {f.stat().st_size/1e6:.1f} MB")
    # Stage 1 upload: source snapshot
    write_stage_readme(qwen_path, "Qwen3.5-2B source snapshot", extra_md="Snapshot of the unmodified upstream model, downloaded as a stable starting point for the ICS quantization run.")
    hf_upload(qwen_path, "dataset", message=f"qwen3.5-2b source snapshot @ {time.strftime('%Y-%m-%d %H:%M')}", blocking=True)

    # 2. Load model in bnb 4-bit for the pipeline
    log("STEP 2: loading model (bnb 4-bit)")
    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
    bnb_cfg = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4", bnb_4bit_compute_dtype=torch.bfloat16)
    t0 = time.time()
    model = AutoModelForCausalLM.from_pretrained(qwen_path, quantization_config=bnb_cfg, device_map="cuda")
    tok = AutoTokenizer.from_pretrained(qwen_path)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    log(f"  loaded in {time.time()-t0:.1f}s; layers={len(model.model.layers)}")

    # 3. Quick smoke test: dequantize ONE layer + forward (sanity)
    log("STEP 3: smoke test — dequantize single layer + forward")
    try:
        from ics.gptq import compute_layer_hessian, gptq_quantize, dequantize_gptq
        # Pick a small layer (first layer's q_proj) for the smoke test
        first_layer = model.model.layers[0]
        # Find a Linear layer in it
        smoke_name = None
        for n, m in first_layer.named_modules():
            if hasattr(m, "weight") and "proj" in n:
                smoke_name = n
                smoke_module = m
                break
        log(f"  smoke target: layers.0.{smoke_name}")
        # Just verify forward on the bnb model
        ids = tok("Hello world. The quick brown fox jumps over the lazy dog. " * 8, return_tensors="pt").input_ids.to("cuda")
        with torch.no_grad():
            out_smoke = model(input_ids=ids, use_cache=False)
        smoke_ok = bool(torch.isfinite(out_smoke.logits).all().item())
        log(f"  smoke forward: finite={smoke_ok}  shape={tuple(out_smoke.logits.shape)}")
        if not smoke_ok:
            raise RuntimeError("smoke forward produced NaN/Inf — aborting")
        del out_smoke, ids
        torch.cuda.empty_cache()
    except Exception as e:
        log(f"  smoke FAILED: {e}")
        raise

    # 4. Run pipeline
    log("STEP 4: ICS+GPTQ pipeline")
    from ics.pipeline import quantize_model, ICSConfig
    from scripts.colab_quantize_ics import DEFAULT_CALIBRATION as CALIB

    cfg = ICSConfig(
        block_size=64, int4_fraction=1.0, int2_fraction=0.0, int1_fraction=0.0,
        method="composite", quant_method="gptq",
        gptq_group_size=128, gptq_percdamp=0.01, gptq_blocksize=128,
        max_calibration_length=256, calibration_texts=CALIB[:24],
        skip_modules=("lm_head", "embed_tokens", "norm", "mtp."),
    )

    t0 = time.time()
    log("  starting pipeline (this can take 30-90 min)...")
    result = quantize_model(model, tok, cfg, device="cuda", show_progress=True)
    elapsed = time.time() - t0
    log(f"  pipeline done in {elapsed:.1f}s; perms={len(result.perms)} quant={len(result.quant)}")

    # 5. Save artifact
    log("STEP 5: saving artifact")
    art = "/content/qwen3.5-2b-ics-gptq-int4"
    from ics.export import save_ics_model
    save_ics_model(result, art, tokenizer=tok, source_model_dir=qwen_path)
    art_size_gb = sum(p.stat().st_size for p in Path(art).rglob("*") if p.is_file()) / 1e9
    log(f"  saved to {art} ({art_size_gb:.2f} GB)")

    # 6. Dequantize back into the model for PPL
    log("STEP 6: dequantize artifact back into model for PPL eval")
    from ics.export import dequantized_state_dict
    sd = dequantized_state_dict(result)
    # Map names back from the export's safe names to the HF names
    name_map = {}
    for k in sd.keys():
        # export uses "__" instead of "." per the safetensors convention
        # but the dequantized_state_dict returns the HF-style names directly
        name_map[k] = k
    # Load into the bnb model: tricky because the bnb modules are Linear4bit.
    # Simplest: dequantize bnb->BF16 first, then assign.
    # For PPL we need a clean dense model — load BF16 separately.
    del model
    torch.cuda.empty_cache()
    log("  cleared bnb model, loading BF16 reference")

    bf16_model = AutoModelForCausalLM.from_pretrained(qwen_path, dtype=torch.bfloat16, device_map="cuda")
    # Now assign dequantized weights into the BF16 model
    missing = bf16_model.load_state_dict(sd, strict=False)
    log(f"  load_state_dict: missing={len(missing.missing_keys)} unexpected={len(missing.unexpected_keys)}")

    # 7. PPL benchmark on wikitext-style text
    log("STEP 7: PPL benchmark")
    EVAL_TEXTS = [
        "Transformers use attention to route information between token positions in a sequence. The model learns to predict the next token from the previous context, and this next-token prediction objective is the basis for most modern language modeling.",
        "Quantization reduces model size by representing weights with fewer bits. The challenge is to preserve accuracy while using lower precision arithmetic. Mixed-precision quantization, where sensitive weights are kept at higher precision, is one approach.",
        "The scientific method involves forming hypotheses, designing experiments to test them, and revising theories based on evidence. In machine learning research, the cycle of benchmark design, model training, and ablation study mirrors this process.",
        "The history of computing traces a path from mechanical calculators to electronic digital computers. Each generation of hardware has enabled new classes of algorithms, from numerical methods to deep learning.",
        "A small benchmark should be deterministic, repeatable, and explicit about its limits. Reporting token count and wall-clock time alongside perplexity is essential for fair comparison.",
    ]
    t0 = time.time()
    ppl, n_tok = compute_perplexity(bf16_model, tok, EVAL_TEXTS, block_size=256, device="cuda")
    log(f"  PPL (ICS+GPTQ+INT4 dequantized): {ppl:.4f} on {n_tok} tokens in {time.time()-t0:.1f}s")

    bench = {
        "model": "Qwen/Qwen3.5-2B",
        "method": "ICS+GPTQ+INT4 (dequantized for PPL)",
        "ppl": ppl,
        "eval_tokens": n_tok,
        "eval_texts": len(EVAL_TEXTS),
        "pipeline_elapsed_s": elapsed,
        "ics_config": {
            "block_size": cfg.block_size,
            "int4_fraction": cfg.int4_fraction,
            "method": cfg.method,
            "quant_method": cfg.quant_method,
            "gptq_group_size": cfg.gptq_group_size,
            "gptq_blocksize": cfg.gptq_blocksize,
        },
        "n_permutations": len(result.perms),
        "n_quantized_layers": len(result.quant),
        "artifact_size_gb": art_size_gb,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
    Path("/content/ppl_results.json").write_text(json.dumps(bench, indent=2))
    log(f"  wrote /content/ppl_results.json")

    # 8. Upload artifact + bench
    write_stage_readme(art, "Qwen3.5-2B ICS+GPTQ+INT4", extra_md=(
        f"Pipeline wall time: {elapsed:.0f}s.\n"
        f"ICS config: block_size={cfg.block_size}, int4_fraction={cfg.int4_fraction}, "
        f"method={cfg.method}, quant_method={cfg.quant_method}, group_size={cfg.gptq_group_size}, "
        f"blocksize={cfg.gptq_blocksize}.\n"
        f"Loads via ics.export.load_ics_model() -> ics.export.dequantized_state_dict(). See ics_meta.json for chain metadata."
    ))
    log("STEP 8: uploading final quantized artifact to model repo")
    hf_upload(art, "model", message=f"qwen3.5-2b ICS+GPTQ+INT4 quantized model @ {time.strftime('%Y-%m-%d %H:%M')}", blocking=True)

    # 9. Upload bench + log to dataset repo
    bench_dir = "/content/_bench_stage"
    Path(bench_dir).mkdir(exist_ok=True)
    Path(bench_dir, "ppl_results.json").write_text(json.dumps(bench, indent=2))
    if Path("/content/pipeline.log").exists():
        shutil.copy2("/content/pipeline.log", Path(bench_dir, "pipeline.log"))
    write_stage_readme(bench_dir, "Qwen3.5-2B ICS+GPTQ+INT4 benchmark + run log", extra_md=(
        f"PPL on a small wikitext-style eval set ({len(EVAL_TEXTS)} texts, {n_tok} tokens).\n"
        f"See ppl_results.json for the JSON form, pipeline.log for the full run log."
    ))
    log("STEP 9: uploading benchmark + run log to dataset repo")
    hf_upload(bench_dir, "dataset", message=f"qwen3.5-2b bench + log @ {time.strftime('%Y-%m-%d %H:%M')}", blocking=True)

    log("===== ALL DONE =====")
    log(f"  model repo: https://huggingface.co/{MODEL_REPO}")
    log(f"  dataset repo: https://huggingface.co/{DATASET_REPO}")
    log(f"  PPL: {ppl:.4f} (eval_tokens={n_tok})")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        log(f"FATAL: {e}")
        log(traceback.format_exc())
        sys.exit(1)