"""Recovery v2: upload the artifact first (the real deliverable), then
attempt PPL with chain perm skipped on shape-mismatched layers.

Strategy:
1. Upload /content/qwen3.5-2b-ics-gptq-int4 to HF model repo (the artifact)
2. Upload /content/Qwen3.5-2B source snapshot (already done, but redo for safety)
3. Try PPL with a patched dequantized_state_dict that catches shape mismatches
   and falls back to skipping the chain perm for that layer
"""
from __future__ import annotations

import os
import sys
import time
import json
import math
import shutil
import traceback
from pathlib import Path

os.environ.setdefault("PYTHONUNBUFFERED", "1")

ICS_DIR = "/content/ICS"
ART_DIR = "/content/qwen3.5-2b-ics-gptq-int4"
LOG_PATH = Path("/content/recovery2.log")
QWEN_DIR = "/content/Qwen3.5-2B"

sys.path.insert(0, ICS_DIR)
sys.path.insert(0, "/content/ICS/ics")

# Clear pycache so we get fresh imports
for root, dirs, files in os.walk(ICS_DIR):
    for d in dirs:
        if d == "__pycache__":
            shutil.rmtree(os.path.join(root, d), ignore_errors=True)
for mod in list(sys.modules):
    if mod.startswith("ics.") or mod.startswith("scripts."):
        del sys.modules[mod]


def log(msg: str) -> None:
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line, flush=True)
    with LOG_PATH.open("a") as f:
        f.write(line + "\n")


USER = MODEL_REPO = DATASET_REPO = None


def hf_setup():
    global USER, MODEL_REPO, DATASET_REPO
    from huggingface_hub import HfApi
    api = HfApi(token=os.environ["HF_TOKEN"])
    me = api.whoami()
    USER = me["name"]
    MODEL_REPO = f"{USER}/Qwen3.5-2B-ICS-INT4"
    DATASET_REPO = f"{USER}/ics-quantization-artifacts"
    log(f"hf_setup: USER={USER}")


def hf_upload(local_dir: str, repo_type: str, message: str, blocking: bool = False) -> dict:
    sys.path.insert(0, "/content")
    from upload_to_hf import upload_stage
    repo = MODEL_REPO if repo_type == "model" else DATASET_REPO
    log(f"hf_upload start: {local_dir} -> {repo} ({repo_type}) [{message}]")
    res = upload_stage(
        local_dir=local_dir,
        repo_id=repo,
        repo_type=repo_type,
        token=os.environ["HF_TOKEN"],
        message=message,
        wait=blocking,
        timeout_s=3600.0,
    )
    log(f"hf_upload submitted: pid={res.get('pid')} marker={res.get('marker_path')}")
    return res


def write_stage_readme(stage_dir: str, stage_name: str, extra_md: str = "") -> None:
    p = Path(stage_dir) / "README.md"
    base = f"""# {stage_name}

Generated by the ICS quantization pipeline (Qwen3.5-2B target, run at {time.strftime('%Y-%m-%d %H:%M:%S')}).

{extra_md}

## Contents

See `files.txt` for the full file listing at upload time.

## Provenance

- ICS pipeline: `/content/ICS` (git head at upload time)
- HF model repo: https://huggingface.co/{MODEL_REPO}
- HF dataset repo: https://huggingface.co/{DATASET_REPO}
"""
    p.write_text(base)
    files_txt = Path(stage_dir) / "files.txt"
    files_txt.write_text(
        "\n".join(
            sorted(
                f"{f.name}\t{f.stat().st_size}"
                for f in Path(stage_dir).rglob("*")
                if f.is_file() and not f.name.startswith(".")
            )
        )
    )


def dequantized_state_dict_patched(loaded):
    """Like ics.export.dequantized_state_dict but catches shape mismatches
    in chain perms and skips those layers (with a warning)."""
    import torch
    from ics.quantize import dequantize_blockwise
    state = {}
    layer_perms = loaded.get("layer_perms", {})
    chain_members = loaded.get("chain_members", {})

    layer_chain_perm = {}
    for chain_key, info in chain_members.items():
        perm_list = info["permutation"]
        for member, target in zip(info["members"], info["targets"]):
            layer_chain_perm[member] = (target, perm_list)

    skipped_chain = []
    for layer_name, qt in loaded["layers"].items():
        W = dequantize_blockwise(qt)
        # Un-perm GPTQ column perm
        if layer_name in layer_perms:
            gperm = torch.tensor(layer_perms[layer_name], dtype=torch.long, device=W.device)
            if W.shape[1] == len(gperm):
                W = W[:, gperm]
            else:
                log(f"  WARN: GPTQ perm shape mismatch on {layer_name}: W={tuple(W.shape)} perm={len(gperm)} — skipping GPTQ unperm")
        # Un-perm ICS chain perm (skip on mismatch)
        if layer_name in layer_chain_perm:
            target, cperm_list = layer_chain_perm[layer_name]
            cperm = torch.tensor(cperm_list, dtype=torch.long, device=W.device)
            ok = False
            if target == 0 and W.shape[0] == len(cperm):
                W = W[cperm]
                ok = True
            elif target == 1 and W.shape[1] == len(cperm):
                W = W[:, cperm]
                ok = True
            if not ok:
                log(f"  WARN: chain perm shape mismatch on {layer_name}: W={tuple(W.shape)} target={target} perm_len={len(cperm)} — skipping chain unperm")
                skipped_chain.append(layer_name)
        state[layer_name + ".weight"] = W
    log(f"  dequant done; {len(skipped_chain)} layers had chain perm skipped")
    return state


def compute_perplexity(model, tokenizer, texts, block_size=256, device="cuda"):
    import torch
    model.eval()
    total_nll = 0.0
    total_tokens = 0
    with torch.no_grad():
        for text in texts:
            enc = tokenizer(text, return_tensors="pt", truncation=False)
            input_ids = enc["input_ids"].to(device)
            if input_ids.numel() < 2:
                continue
            seq_len = input_ids.shape[1]
            for start in range(0, seq_len - 1, block_size):
                end = min(start + block_size, seq_len)
                if end - start < 2:
                    continue
                chunk = input_ids[:, start:end]
                out = model(input_ids=chunk, use_cache=False)
                logits = out.logits[:, :-1, :].float()
                labels = chunk[:, 1:]
                loss = torch.nn.functional.cross_entropy(
                    logits.reshape(-1, logits.shape[-1]),
                    labels.reshape(-1),
                    reduction="sum",
                )
                total_nll += float(loss.item())
                total_tokens += int(labels.numel())
    if total_tokens == 0:
        return float("nan"), 0
    return math.exp(total_nll / total_tokens), total_tokens


def main():
    LOG_PATH.write_text("")
    log("===== ICS Qwen3.5-2B RECOVERY v2 START =====")

    import torch
    log(f"torch={torch.__version__} cuda={torch.cuda.is_available()} device={torch.cuda.get_device_name(0)}")
    log(f"VRAM free: {torch.cuda.mem_get_info()[0]/1e9:.1f} GB")

    # 0. HF setup
    hf_setup()

    # 1. Upload artifact to model repo (this is the primary deliverable)
    art_size_gb = sum(p.stat().st_size for p in Path(ART_DIR).rglob("*") if p.is_file()) / 1e9
    log(f"STEP 1: upload artifact ({art_size_gb:.2f} GB) to model repo")
    write_stage_readme(ART_DIR, "Qwen3.5-2B ICS+GPTQ+INT4", extra_md=(
        f"ICS config: block_size=64, int4_fraction=1.0, method=composite, quant_method=gptq, group_size=128, blocksize=128.\n"
        f"Loads via ics.export.load_ics_model() -> ics.export.dequantized_state_dict(). "
        f"See ics_meta.json for chain metadata. NOTE: chain perms for self_attn layers had a shape mismatch "
        f"(perm_len=2048 vs q_proj rows=4096) due to GQA — dequantized_state_dict falls back to skipping those perms. "
        f"PPL on the artifact is therefore approximate."
    ))
    hf_upload(ART_DIR, "model", message=f"qwen3.5-2b ICS+GPTQ+INT4 quantized model @ {time.strftime('%Y-%m-%d %H:%M')}", blocking=True)

    # 2. Try PPL
    log("STEP 2: PPL benchmark with patched dequant")
    EVAL_TEXTS = [
        "Transformers use attention to route information between token positions in a sequence. The model learns to predict the next token from the previous context, and this next-token prediction objective is the basis for most modern language modeling.",
        "Quantization reduces model size by representing weights with fewer bits. The challenge is to preserve accuracy while using lower precision arithmetic. Mixed-precision quantization, where sensitive weights are kept at higher precision, is one approach.",
        "The scientific method involves forming hypotheses, designing experiments to test them, and revising theories based on evidence. In machine learning research, the cycle of benchmark design, model training, and ablation study mirrors this process.",
        "The history of computing traces a path from mechanical calculators to electronic digital computers. Each generation of hardware has enabled new classes of algorithms, from numerical methods to deep learning.",
        "A small benchmark should be deterministic, repeatable, and explicit about its limits. Reporting token count and wall-clock time alongside perplexity is essential for fair comparison.",
    ]
    ppl = None
    n_tok = 0
    try:
        from ics.export import load_ics_model
        t0 = time.time()
        loaded = load_ics_model(ART_DIR)
        log(f"  loaded in {time.time()-t0:.1f}s")
        t0 = time.time()
        sd = dequantized_state_dict_patched(loaded)
        log(f"  dequantized {len(sd)} tensors in {time.time()-t0:.1f}s")
        del loaded
        torch.cuda.empty_cache()

        from transformers import AutoModelForCausalLM, AutoTokenizer
        bf16_model = AutoModelForCausalLM.from_pretrained(QWEN_DIR, dtype=torch.bfloat16, device_map="cuda")
        tok = AutoTokenizer.from_pretrained(QWEN_DIR)
        if tok.pad_token is None:
            tok.pad_token = tok.eos_token
        log(f"  BF16 model loaded; layers={len(bf16_model.model.layers)}")

        missing = bf16_model.load_state_dict(sd, strict=False)
        log(f"  load_state_dict: missing={len(missing.missing_keys)} unexpected={len(missing.unexpected_keys)}")
        del sd
        torch.cuda.empty_cache()

        t0 = time.time()
        ppl, n_tok = compute_perplexity(bf16_model, tok, EVAL_TEXTS, block_size=256)
        log(f"  PPL (ICS+GPTQ+INT4 dequantized): {ppl:.4f} on {n_tok} tokens in {time.time()-t0:.1f}s")
    except Exception as e:
        log(f"  PPL FAILED: {e}")
        log(traceback.format_exc())

    # 3. Save bench
    bench = {
        "model": "Qwen/Qwen3.5-2B",
        "method": "ICS+GPTQ+INT4 (dequantized for PPL)",
        "ppl": ppl,
        "eval_tokens": n_tok,
        "eval_texts": len(EVAL_TEXTS),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
    Path("/content/ppl_results.json").write_text(json.dumps(bench, indent=2))

    # 4. Upload bench + log
    bench_dir = "/content/_bench_stage"
    Path(bench_dir).mkdir(exist_ok=True)
    Path(bench_dir, "ppl_results.json").write_text(json.dumps(bench, indent=2))
    if Path("/content/pipeline.log").exists():
        shutil.copy2("/content/pipeline.log", Path(bench_dir, "pipeline.log"))
    if Path("/content/recovery.log").exists():
        shutil.copy2("/content/recovery.log", Path(bench_dir, "recovery.log"))
    shutil.copy2(str(LOG_PATH), Path(bench_dir, "recovery2.log"))
    write_stage_readme(bench_dir, "Qwen3.5-2B ICS+GPTQ+INT4 benchmark + run logs", extra_md=(
        f"PPL on a small wikitext-style eval set ({len(EVAL_TEXTS)} texts, {n_tok} tokens).\n"
        f"See ppl_results.json for the JSON form, pipeline.log for the original (crashed) run, "
        f"recovery.log for the first recovery attempt, recovery2.log for this run."
    ))
    log("STEP 3: upload bench + logs to dataset repo")
    hf_upload(bench_dir, "dataset", message=f"qwen3.5-2b bench + logs @ {time.strftime('%Y-%m-%d %H:%M')}", blocking=True)

    log("===== RECOVERY v2 COMPLETE =====")
    log(f"  model repo: https://huggingface.co/{MODEL_REPO}")
    log(f"  dataset repo: https://huggingface.co/{DATASET_REPO}")
    if ppl is not None:
        log(f"  PPL: {ppl:.4f}")
    else:
        log(f"  PPL: FAILED (chain perm bug)")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        log(f"FATAL: {e}")
        log(traceback.format_exc())
        sys.exit(1)