"""Recovery: the GPTQ run produced the artifact at /content/qwen3.5-2b-ics-gptq-int4
but the pipeline crashed on the PPL step. This script:
1. Loads the saved ICS artifact
2. Dequantizes it back into a BF16 model
3. Computes PPL
4. Uploads the artifact + bench to HF

Push to Colab as /content/run_recovery.py, then launch as nohup subprocess.
"""
from __future__ import annotations

import os
import sys
import time
import json
import math
import shutil
import traceback
from pathlib import Path

os.environ.setdefault("PYTHONUNBUFFERED", "1")

ICS_DIR = "/content/ICS"
ART_DIR = "/content/qwen3.5-2b-ics-gptq-int4"
LOG_PATH = Path("/content/recovery.log")
QWEN_DIR = "/content/Qwen3.5-2B"

sys.path.insert(0, ICS_DIR)
for root, dirs, files in os.walk(ICS_DIR):
    for d in dirs:
        if d == "__pycache__":
            shutil.rmtree(os.path.join(root, d), ignore_errors=True)
for mod in list(sys.modules):
    if mod.startswith("ics.") or mod.startswith("scripts."):
        del sys.modules[mod]


def log(msg: str) -> None:
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line, flush=True)
    with LOG_PATH.open("a") as f:
        f.write(line + "\n")


def hf_setup():
    global USER, MODEL_REPO, DATASET_REPO
    from huggingface_hub import HfApi
    api = HfApi(token=os.environ["HF_TOKEN"])
    me = api.whoami()
    USER = me["name"]
    MODEL_REPO = f"{USER}/Qwen3.5-2B-ICS-INT4"
    DATASET_REPO = f"{USER}/ics-quantization-artifacts"
    log(f"hf_setup: USER={USER} MODEL_REPO={MODEL_REPO} DATASET_REPO={DATASET_REPO}")


def hf_upload(local_dir: str, repo_type: str, message: str, blocking: bool = False) -> dict:
    sys.path.insert(0, "/content")
    from upload_to_hf import upload_stage
    repo = MODEL_REPO if repo_type == "model" else DATASET_REPO
    log(f"hf_upload start: {local_dir} -> {repo} ({repo_type}) [{message}]")
    res = upload_stage(
        local_dir=local_dir,
        repo_id=repo,
        repo_type=repo_type,
        token=os.environ["HF_TOKEN"],
        message=message,
        wait=blocking,
        timeout_s=3600.0,
    )
    log(f"hf_upload submitted: pid={res.get('pid')} marker={res.get('marker_path')}")
    return res


def write_stage_readme(stage_dir: str, stage_name: str, extra_md: str = "") -> None:
    p = Path(stage_dir) / "README.md"
    base = f"""# {stage_name}

Generated by the ICS quantization pipeline (Qwen3.5-2B target, run at {time.strftime('%Y-%m-%d %H:%M:%S')}).

{extra_md}

## Contents

See `files.txt` for the full file listing at upload time.

## Provenance

- ICS pipeline: `/content/ICS` (git head at upload time)
- HF model repo: https://huggingface.co/{MODEL_REPO}
- HF dataset repo: https://huggingface.co/{DATASET_REPO}
"""
    p.write_text(base)
    files_txt = Path(stage_dir) / "files.txt"
    files_txt.write_text(
        "\n".join(
            sorted(
                f"{f.name}\t{f.stat().st_size}"
                for f in Path(stage_dir).rglob("*")
                if f.is_file() and not f.name.startswith(".")
            )
        )
    )


def compute_perplexity(model, tokenizer, texts: list[str], block_size: int = 512, device: str = "cuda") -> tuple[float, int]:
    import torch
    model.eval()
    total_nll = 0.0
    total_tokens = 0
    with torch.no_grad():
        for text in texts:
            enc = tokenizer(text, return_tensors="pt", truncation=False)
            input_ids = enc["input_ids"].to(device)
            if input_ids.numel() < 2:
                continue
            seq_len = input_ids.shape[1]
            for start in range(0, seq_len - 1, block_size):
                end = min(start + block_size, seq_len)
                if end - start < 2:
                    continue
                chunk = input_ids[:, start:end]
                out = model(input_ids=chunk, use_cache=False)
                logits = out.logits[:, :-1, :].float()
                labels = chunk[:, 1:]
                loss = torch.nn.functional.cross_entropy(
                    logits.reshape(-1, logits.shape[-1]),
                    labels.reshape(-1),
                    reduction="sum",
                )
                total_nll += float(loss.item())
                total_tokens += int(labels.numel())
    if total_tokens == 0:
        return float("nan"), 0
    return math.exp(total_nll / total_tokens), total_tokens


def main():
    LOG_PATH.write_text("")
    log("===== ICS Qwen3.5-2B RECOVERY START =====")

    import torch
    log(f"torch={torch.__version__} cuda={torch.cuda.is_available()} device={torch.cuda.get_device_name(0)}")
    log(f"VRAM free: {torch.cuda.mem_get_info()[0]/1e9:.1f} GB / {torch.cuda.mem_get_info()[1]/1e9:.1f} GB")

    # Check artifact exists
    art = Path(ART_DIR)
    if not art.exists():
        log(f"FATAL: artifact dir {ART_DIR} does not exist — need to re-run pipeline")
        sys.exit(1)
    files = sorted(art.iterdir())
    log(f"artifact dir has {len(files)} entries")
    for f in files[:15]:
        sz = f.stat().st_size if f.is_file() else 0
        log(f"  {f.name}: {sz/1e6:.2f} MB")

    # 1. HF setup
    hf_setup()

    # 2. Load artifact + dequantize
    log("STEP 1: load ICS artifact + dequantize state dict")
    from ics.export import load_ics_model, dequantized_state_dict
    t0 = time.time()
    loaded = load_ics_model(ART_DIR)
    log(f"  loaded in {time.time()-t0:.1f}s; keys={list(loaded.keys())}")
    t0 = time.time()
    sd = dequantized_state_dict(loaded)
    log(f"  dequantized {len(sd)} tensors in {time.time()-t0:.1f}s")
    del loaded
    torch.cuda.empty_cache()

    # 3. Load BF16 model + assign dequantized weights
    log("STEP 2: load BF16 model + assign dequantized weights")
    from transformers import AutoModelForCausalLM, AutoTokenizer
    bf16_model = AutoModelForCausalLM.from_pretrained(QWEN_DIR, dtype=torch.bfloat16, device_map="cuda")
    tok = AutoTokenizer.from_pretrained(QWEN_DIR)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    log(f"  model loaded; n_layers={len(bf16_model.model.layers)}")

    missing = bf16_model.load_state_dict(sd, strict=False)
    log(f"  load_state_dict: missing={len(missing.missing_keys)} unexpected={len(missing.unexpected_keys)}")
    if missing.missing_keys:
        log(f"  first missing: {missing.missing_keys[:5]}")
    if missing.unexpected_keys:
        log(f"  first unexpected: {missing.unexpected_keys[:5]}")
    del sd
    torch.cuda.empty_cache()

    # 4. PPL benchmark
    log("STEP 3: PPL benchmark")
    EVAL_TEXTS = [
        "Transformers use attention to route information between token positions in a sequence. The model learns to predict the next token from the previous context, and this next-token prediction objective is the basis for most modern language modeling.",
        "Quantization reduces model size by representing weights with fewer bits. The challenge is to preserve accuracy while using lower precision arithmetic. Mixed-precision quantization, where sensitive weights are kept at higher precision, is one approach.",
        "The scientific method involves forming hypotheses, designing experiments to test them, and revising theories based on evidence. In machine learning research, the cycle of benchmark design, model training, and ablation study mirrors this process.",
        "The history of computing traces a path from mechanical calculators to electronic digital computers. Each generation of hardware has enabled new classes of algorithms, from numerical methods to deep learning.",
        "A small benchmark should be deterministic, repeatable, and explicit about its limits. Reporting token count and wall-clock time alongside perplexity is essential for fair comparison.",
    ]
    t0 = time.time()
    ppl, n_tok = compute_perplexity(bf16_model, tok, EVAL_TEXTS, block_size=256, device="cuda")
    log(f"  PPL (ICS+GPTQ+INT4 dequantized): {ppl:.4f} on {n_tok} tokens in {time.time()-t0:.1f}s")

    # 5. Save bench JSON
    bench = {
        "model": "Qwen/Qwen3.5-2B",
        "method": "ICS+GPTQ+INT4 (dequantized for PPL)",
        "ppl": ppl,
        "eval_tokens": n_tok,
        "eval_texts": len(EVAL_TEXTS),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
    Path("/content/ppl_results.json").write_text(json.dumps(bench, indent=2))

    # 6. Upload artifact (model repo)
    art_size_gb = sum(p.stat().st_size for p in Path(ART_DIR).rglob("*") if p.is_file()) / 1e9
    log(f"STEP 4: upload artifact ({art_size_gb:.2f} GB) to model repo")
    write_stage_readme(ART_DIR, "Qwen3.5-2B ICS+GPTQ+INT4", extra_md=(
        f"Pipeline crashed during PPL eval but the quantized artifact was saved before the crash. This upload is the recovery.\n"
        f"ICS config: block_size=64, int4_fraction=1.0, method=composite, quant_method=gptq, group_size=128, blocksize=128.\n"
        f"Loads via ics.export.load_ics_model() -> ics.export.dequantized_state_dict(). See ics_meta.json for chain metadata."
    ))
    hf_upload(ART_DIR, "model", message=f"qwen3.5-2b ICS+GPTQ+INT4 quantized model @ {time.strftime('%Y-%m-%d %H:%M')}", blocking=True)

    # 7. Upload bench + log to dataset repo
    bench_dir = "/content/_bench_stage"
    Path(bench_dir).mkdir(exist_ok=True)
    Path(bench_dir, "ppl_results.json").write_text(json.dumps(bench, indent=2))
    if Path("/content/pipeline.log").exists():
        shutil.copy2("/content/pipeline.log", Path(bench_dir, "pipeline.log"))
    if Path("/content/recovery.log").exists():
        shutil.copy2("/content/recovery.log", Path(bench_dir, "recovery.log"))
    write_stage_readme(bench_dir, "Qwen3.5-2B ICS+GPTQ+INT4 benchmark + run logs", extra_md=(
        f"PPL on a small wikitext-style eval set ({len(EVAL_TEXTS)} texts, {n_tok} tokens).\n"
        f"See ppl_results.json for the JSON form, pipeline.log for the original (crashed) run log, recovery.log for this run."
    ))
    log("STEP 5: upload bench + logs to dataset repo")
    hf_upload(bench_dir, "dataset", message=f"qwen3.5-2b bench + logs @ {time.strftime('%Y-%m-%d %H:%M')}", blocking=True)

    log("===== RECOVERY COMPLETE =====")
    log(f"  model repo: https://huggingface.co/{MODEL_REPO}")
    log(f"  dataset repo: https://huggingface.co/{DATASET_REPO}")
    log(f"  PPL: {ppl:.4f} (eval_tokens={n_tok})")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        log(f"FATAL: {e}")
        log(traceback.format_exc())
        sys.exit(1)